name: Chore
description: 杂项/文档/构建/治理
title: "[Chore] "
labels: ["chore"]
body:
  - type: input
    id: owner
    attributes:
      label: Owner
      placeholder: "@ZK-Andy"
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: [p0, p1, p2, p3]
      default: 1
    validations:
      required: true
  - type: dropdown
    id: class
    attributes:
      label: Class
      options: [process, testing, simplification, architecture]
      default: 0
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Task
      description: 任务描述
    validations:
      required: true
